"""Generator sub-agent: plan steps in, executable Playwright tests out.

The hard part of test generation is not writing Python - it is not writing
Python that references elements which do not exist. So generation happens in
three passes:

1. **Live walk.** The flow is walked in a real browser. Before each step, the
   step's plain-language target is resolved against the *current* DOM by
   :mod:`browser.selectors`, and non-assertion steps are then performed so the
   next step is resolved against the page state it will actually meet. Nothing
   reaches the code writer that has not been proved to exist.

2. **Model authoring.** The small, fast model writes the test body from the
   flow plus the resolved locators. Judgment already happened upstream; this is
   mechanical translation, so it must never burn the 70B.

3. **Gate and fall back.** The output is AST-audited
   (:mod:`browser.sandbox`), scanned for credential literals, and checked for
   assertions. Invalid output earns exactly one repair round-trip. If it still
   fails, a deterministic compiler renders the *same validated steps and
   locators* into source, and the report records ``generated_by_model`` as the
   fallback compiler so nobody mistakes it for model output.

The fallback is a compiler over agent-produced artifacts, not a hand-written
test: its input is the agent's plan and the agent's live-resolved selectors,
and no human ever edits its output.

Trade-off, stated plainly: the live walk *interacts* with the target - it
clicks and fills. Point this agent at a staging or demo environment, not at
production data you care about.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Sequence

from browser.crawler import inventory_for_url
from browser.sandbox import validate_test_source
from browser.selectors import escape_py_string, resolve_target
from browser.session import BrowserSession
from config import Settings, get_settings
from graph.runtime import RunContext
from graph.state import (
    GeneratedTest,
    RiskLevel,
    SelectorValidation,
    SiteMap,
    TestFlow,
    TestStep,
)
from llm.client import LLMClient, ModelRole
from llm.json_utils import JSONParseError
from llm.prompts import GENERATOR_SYSTEM, generator_user
from logging_setup import get_logger
from security import assert_no_secret_literals, redact_text, sanitize_url

log = get_logger("aivor.generator")

# Steps that change page state during the live walk. Assertions are never
# performed during generation - they are what the test is for.
INTERACTIVE_ACTIONS = {"goto", "click", "fill", "select", "check", "press"}
ASSERTION_ACTIONS = {"assert_text", "assert_visible", "assert_not_visible", "assert_url"}

# Placeholders a planner may leave where a credential belongs. They are
# rewritten into a runtime secret lookup; a literal is never emitted.
SECRET_PLACEHOLDER_RE = re.compile(
    r"\{\{\s*(username|user|email|password|token)\s*\}\}|<\s*(username|user|email|password|token)\s*>",
    re.I,
)

FILE_HEADER = '''"""Auto-generated by the Autonomous Test Orchestration Agent - DO NOT EDIT.

Flow      : {flow_id} - {flow_name}
Category  : {category}
Risk      : {risk}
Expected  : {expected}
Generated : {generated_at} by {model}

Every locator below was resolved against the live application before this file
was written. Credentials are never embedded: a test that needs one calls
``ctx["secret"]("username")``, which the runtime resolves from the in-memory
secret store (or, under plain pytest, from the LOGIN_USERNAME / LOGIN_PASSWORD
environment variables - see the generated conftest.py).
"""

from __future__ import annotations

import re

from playwright.async_api import expect

FLOW_ID = "{flow_id}"
FLOW_NAME = "{flow_name_lit}"
FLOW_CATEGORY = "{category}"
FLOW_RISK = "{risk}"
EXPECTED_OUTCOME = "{expected_lit}"


'''

CONFTEST_SOURCE = '''"""Pytest harness for the agent-generated tests in this directory.

Generated by the Autonomous Test Orchestration Agent so that the suite it wrote
can also be run by a human with plain ``pytest`` - no agent, no API key:

    pip install pytest pytest-asyncio playwright
    playwright install chromium
    LOGIN_USERNAME=... LOGIN_PASSWORD=... pytest -q

Credentials are read from the environment here. They are never written into a
test file.
"""

from __future__ import annotations

import os

import pytest
import pytest_asyncio
from playwright.async_api import async_playwright

HEADLESS = os.environ.get("HEADLESS", "true").lower() not in ("0", "false", "no")
STORAGE_STATE = os.environ.get("STORAGE_STATE") or None

_SECRET_ENV = {
    "username": "LOGIN_USERNAME",
    "user": "LOGIN_USERNAME",
    "email": "LOGIN_USERNAME",
    "password": "LOGIN_PASSWORD",
    "token": "LOGIN_TOKEN",
}


@pytest_asyncio.fixture
async def page():
    """A fresh browser, context and page per test.

    Function-scoped on purpose. A session-scoped browser would be faster, but
    a session-scoped async fixture has to share an event loop with the tests,
    and getting that wrong under pytest-asyncio hangs the whole suite with no
    output. Each test paying ~1s of launch cost is a good trade for a harness
    that always runs. It also guarantees flow isolation: no test can inherit
    cookies or local storage from the one before it.
    """
    async with async_playwright() as playwright:
        browser = await playwright.chromium.launch(headless=HEADLESS)
        options = {"viewport": {"width": 1280, "height": 900}, "ignore_https_errors": True}
        if STORAGE_STATE and os.path.exists(STORAGE_STATE):
            options["storage_state"] = STORAGE_STATE
        context = await browser.new_context(**options)
        context.set_default_timeout(8000)
        page = await context.new_page()
        try:
            yield page
        finally:
            await context.close()
            await browser.close()


@pytest.fixture
def ctx():
    """Runtime context injected into every generated test."""

    def secret(name: str) -> str:
        return os.environ.get(_SECRET_ENV.get((name or "").lower(), ""), "")

    return {
        "secret": secret,
        "base_url": os.environ.get("TARGET_URL", ""),
        "timeout_ms": 8000,
    }
'''

PYTEST_INI = """[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
addopts = -q
"""


# ==========================================================================
# Live selector walk
# ==========================================================================
async def resolve_flow_selectors(
    session: BrowserSession,
    *,
    ctx: RunContext,
    flow: TestFlow,
    site_map: SiteMap | None,
    settings: Settings | None = None,
) -> list[SelectorValidation]:
    """Walk the flow in a real browser, resolving one target per step.

    Interactive steps are executed after their target resolves so that later
    steps are resolved against the page they will really run on. A step that
    cannot be performed does not abort the walk: the remaining steps are still
    resolved against whatever page is on screen, and the failure is recorded in
    the validation note.
    """
    cfg = settings or get_settings()
    validations: list[SelectorValidation] = []

    context = await session.new_context()
    page = await context.new_page()
    try:
        try:
            await page.goto(
                flow.url or (site_map.target_url if site_map else ""),
                timeout=cfg.nav_timeout_ms,
                wait_until="domcontentloaded",
            )
        except Exception as exc:
            log.info("flow %s: could not open %s (%s)", flow.id, sanitize_url(flow.url), exc)

        for index, step in enumerate(flow.steps):
            inventory = inventory_for_url(site_map, _current_url(page)) if site_map else {}
            validation = await resolve_target(
                page,
                step_index=index,
                intent=step.target if step.action != "goto" else "",
                action=step.action,
                page_inventory=inventory,
                max_candidates=cfg.selector_validation_candidates + 4,
            )
            validations.append(validation)

            if step.action in INTERACTIVE_ACTIONS:
                performed = await _perform(page, step, validation, cfg)
                if not performed and validation.valid:
                    validation.note = (
                        f"{validation.note} | resolved but the action could not be "
                        "performed during the generation walk"
                    ).strip(" |")
        return validations
    finally:
        try:
            await context.close()
        except Exception:  # pragma: no cover
            log.debug("generation context close failed", exc_info=True)


async def _perform(page: Any, step: TestStep, validation: SelectorValidation, cfg: Settings) -> bool:
    """Advance the page state during the generation walk. Never raises."""
    try:
        if step.action == "goto":
            url = step.target or step.value or ""
            if url:
                await page.goto(url, timeout=cfg.nav_timeout_ms, wait_until="domcontentloaded")
            return True
        if not validation.valid or not validation.chosen:
            return False

        locator = _eval_locator(page, validation.chosen)
        if locator is None:
            return False
        value = _resolved_value(step)
        if step.action == "click":
            await locator.click(timeout=cfg.action_timeout_ms)
        elif step.action == "fill":
            await locator.fill(value or "", timeout=cfg.action_timeout_ms)
        elif step.action == "select":
            await locator.select_option(value or "", timeout=cfg.action_timeout_ms)
        elif step.action == "check":
            await locator.check(timeout=cfg.action_timeout_ms)
        elif step.action == "press":
            await locator.press(value or "Enter", timeout=cfg.action_timeout_ms)
        try:
            await page.wait_for_load_state("domcontentloaded", timeout=5000)
        except Exception:
            pass
        return True
    except Exception as exc:
        log.debug("generation walk step %s failed: %s", step.action, exc)
        return False


def _eval_locator(page: Any, expression: str) -> Any:
    """Turn a locator source expression back into a live locator.

    Uses the structured parser rather than ``eval``; an expression we cannot
    parse simply yields ``None`` and the walk continues.
    """
    from browser.selectors import _locator_from, parse_expression  # local import: internal helper

    parsed = parse_expression(expression)
    if parsed is None:
        return None
    try:
        locator = _locator_from(page, parsed)
        return locator.first if expression.rstrip().endswith(".first") else locator
    except Exception:
        return None


def _current_url(page: Any) -> str:
    try:
        return page.url or ""
    except Exception:  # pragma: no cover
        return ""


def _resolved_value(step: TestStep) -> str:
    """The literal a step should type, with credential placeholders removed."""
    value = step.value or ""
    if SECRET_PLACEHOLDER_RE.search(value):
        return ""
    return value


# ==========================================================================
# Code generation
# ==========================================================================
async def generate_test(
    ctx: RunContext,
    llm: LLMClient,
    *,
    flow: TestFlow,
    validations: Sequence[SelectorValidation],
    risk: RiskLevel,
    base_url: str,
    settings: Settings | None = None,
) -> GeneratedTest:
    """Produce one executable test file for one flow.

    Model-authored source is preferred; the deterministic compiler is the
    documented fallback. Either way the result is audited before it is written.
    """
    cfg = settings or get_settings()
    resolved = [_validation_for_prompt(v, flow.steps) for v in validations]

    result = GeneratedTest(
        flow_id=flow.id,
        flow_name=flow.name,
        module_name=f"test_{_slug(flow.id)}_{_slug(flow.name)[:40]}",
        generated_by_model=cfg.model_codegen,
    )

    unresolved = [
        v for v, step in zip(validations, flow.steps)
        if not v.valid and step.action in INTERACTIVE_ACTIONS and step.action != "goto"
    ]
    if unresolved:
        result.warnings.append(
            f"{len(unresolved)} interactive step(s) could not be resolved against the "
            "live page; the test is generated defensively around them"
        )

    messages = [
        {"role": "system", "content": GENERATOR_SYSTEM},
        {
            "role": "user",
            "content": generator_user(
                flow=flow.model_dump(mode="json"),
                resolved_steps=resolved,
                risk=risk.value,
                base_url=base_url,
                credentials_present=ctx.credentials_present,
            ),
        },
    ]

    source = ""
    try:
        payload = await llm.complete_json(
            ModelRole.CODEGEN, messages, task=f"generator:{flow.id}", max_tokens=3000
        )
        if isinstance(payload, dict):
            source = str(payload.get("test_source") or "")
            for note in payload.get("notes") or []:
                result.warnings.append(f"model note: {str(note)[:200]}")
    except (JSONParseError, Exception) as exc:  # noqa: B014 - deliberate broad catch
        log.warning("codegen failed for %s: %s", flow.id, exc)
        result.warnings.append(f"model codegen failed ({type(exc).__name__}); using the compiler")

    source = _strip_imports(source)
    verdict = validate_test_source(source) if source.strip() else None

    # One repair round-trip on invalid model output, exactly as the JSON path does.
    if source.strip() and verdict is not None and not verdict.ok:
        result.repair_attempts = 1
        log.info("flow %s: repairing generated source (%s)", flow.id, verdict.summary())
        try:
            repair = await llm.complete_json(
                ModelRole.CODEGEN,
                [
                    *messages,
                    {"role": "assistant", "content": source[:3000]},
                    {
                        "role": "user",
                        "content": (
                            "The code you produced was rejected by the safety and syntax "
                            f"audit with these errors:\n{chr(10).join(verdict.errors[:6])}\n"
                            "Return the corrected function using the same JSON schema. "
                            "Emit no import statements and use only the resolved locators."
                        ),
                    },
                ],
                task=f"generator:{flow.id}:repair",
                max_tokens=3000,
            )
            if isinstance(repair, dict):
                repaired = _strip_imports(str(repair.get("test_source") or ""))
                if repaired.strip():
                    repaired_verdict = validate_test_source(repaired)
                    if repaired_verdict.ok:
                        source, verdict = repaired, repaired_verdict
        except Exception as exc:
            log.warning("repair round-trip failed for %s: %s", flow.id, exc)

    leaked = assert_no_secret_literals(source, ctx.run_id) if source else []
    if leaked:
        # A model that embedded a real credential is not trusted for this flow.
        result.warnings.append(
            f"model output embedded credential literal(s) ({', '.join(leaked)}); "
            "output discarded and the deterministic compiler used instead"
        )
        ctx.emit(
            "generator",
            "decision",
            f"{flow.id}: discarded model output that embedded a credential literal",
            detail="the deterministic compiler was used instead; no secret reached disk",
            flow_id=flow.id,
            confidence=1.0,
            needs_human_review=True,
        )
        source, verdict = "", None

    if not source.strip() or (verdict is not None and not verdict.ok):
        compiled, warnings, blocking = compile_steps_to_source(flow, validations)
        result.warnings.extend(warnings)
        if blocking:
            result.valid = False
            result.validation_error = blocking
            result.source = ""
            return result
        source = compiled
        result.generated_by_model = "deterministic-compiler-fallback"
        verdict = validate_test_source(source)

    if verdict is not None and not verdict.ok:
        result.valid = False
        result.validation_error = verdict.summary()
        result.source = source
        return result

    if verdict is not None:
        result.warnings.extend(verdict.warnings)

    result.source = source
    result.selector_validations = list(validations)
    result.valid = True
    return result


def _validation_for_prompt(validation: SelectorValidation, steps: Sequence[TestStep]) -> dict[str, Any]:
    step = steps[validation.step_index] if validation.step_index < len(steps) else None
    return {
        "step_index": validation.step_index,
        "action": step.action if step else "",
        "target_description": validation.intent,
        "value": _resolved_value(step) if step else "",
        "resolved": validation.valid,
        "locator": validation.chosen,
        "strategy": validation.chosen_strategy,
        "note": validation.note,
    }


def _strip_imports(source: str) -> str:
    """Remove import lines from model output; the header supplies them."""
    if not source:
        return ""
    kept = [
        line
        for line in source.splitlines()
        if not re.match(r"^\s*(from\s+\S+\s+)?import\s+", line)
    ]
    return "\n".join(kept).strip("\n")


# ==========================================================================
# Deterministic compiler (fallback path)
# ==========================================================================
def compile_steps_to_source(
    flow: TestFlow,
    validations: Sequence[SelectorValidation],
) -> tuple[str, list[str], str | None]:
    """Render validated steps + resolved locators into Playwright source.

    Returns ``(source, warnings, blocking_error)``. ``blocking_error`` is set
    when a required interactive step has no resolvable locator: rather than
    emit a test that only pretends to exercise the flow, the flow is reported
    as un-generatable and shows up in the report as a remaining coverage gap.
    """
    lines: list[str] = [
        "async def test_flow(page, ctx):",
        f'    """{_docstring(flow)}"""',
    ]
    warnings: list[str] = []
    by_index = {v.step_index: v for v in validations}
    asserted = False

    for index, step in enumerate(flow.steps):
        validation = by_index.get(index)
        locator = validation.chosen if (validation and validation.valid) else None
        comment = f"    # step {index + 1}: {step.description or step.action}"
        lines.append(comment)

        if step.action == "goto":
            url = step.target or step.value or flow.url
            lines.append(
                f'    await page.goto("{escape_py_string(url)}", wait_until="domcontentloaded")'
            )
            continue

        if step.action == "screenshot":
            lines.append("    # screenshots are captured by the runner, not by the test")
            continue

        if step.action == "assert_url":
            expected = step.value or step.target or flow.url
            lines.append(
                f'    await expect(page).to_have_url(re.compile(r"{_regex_literal(expected)}"))'
            )
            asserted = True
            continue

        if locator is None:
            if step.action in INTERACTIVE_ACTIONS:
                return (
                    "",
                    warnings,
                    (
                        f"step {index + 1} ({step.action} on {step.target!r}) could not be "
                        "resolved against the live application, so no honest test can be "
                        "compiled for this flow"
                    ),
                )
            # An unresolvable assertion degrades to a page-level text check when
            # the plan gave us literal text to look for, and is skipped otherwise.
            literal = step.value or _quoted_literal(step.target)
            if literal:
                lines.append(
                    f'    await expect(page.locator("body")).to_contain_text('
                    f'"{escape_py_string(literal)}", timeout=8000)'
                )
                warnings.append(
                    f"step {index + 1}: element not resolvable; degraded to a page-level "
                    f"text assertion for {literal!r}"
                )
                asserted = True
            else:
                lines.append(
                    f"    # step {index + 1} skipped: target {step.target!r} could not be "
                    "resolved and carried no literal text to assert on"
                )
                warnings.append(
                    f"step {index + 1}: assertion dropped, target unresolvable and untyped"
                )
            continue

        value_expr = _value_expression(step)
        if step.action == "click":
            lines.append(f"    await {locator}.click(timeout=8000)")
        elif step.action == "fill":
            lines.append(f"    await {locator}.fill({value_expr}, timeout=8000)")
        elif step.action == "select":
            lines.append(f"    await {locator}.select_option({value_expr}, timeout=8000)")
        elif step.action == "check":
            lines.append(f"    await {locator}.check(timeout=8000)")
        elif step.action == "press":
            key = step.value or "Enter"
            lines.append(f'    await {locator}.press("{escape_py_string(key)}", timeout=8000)')
        elif step.action in ("wait_for", "assert_visible"):
            lines.append(f"    await expect({locator}).to_be_visible(timeout=8000)")
            asserted = True
        elif step.action == "assert_not_visible":
            lines.append(f"    await expect({locator}).to_be_hidden(timeout=8000)")
            asserted = True
        elif step.action == "assert_text":
            expected = step.value or _quoted_literal(step.target) or step.target
            lines.append(
                f"    await expect({locator}).to_contain_text("
                f'"{escape_py_string(expected)}", timeout=8000)'
            )
            asserted = True
        else:  # pragma: no cover - VALID_ACTIONS is exhaustive upstream
            lines.append(f"    # unsupported action {step.action!r} skipped")

    if not asserted:
        # A test with no assertion can only fail on an exception, which makes it
        # nearly worthless. Close on the flow's stated expected outcome.
        literal = _quoted_literal(flow.expected_outcome)
        if literal:
            lines.append("    # closing assertion derived from the flow's expected outcome")
            lines.append(
                f'    await expect(page.locator("body")).to_contain_text('
                f'"{escape_py_string(literal)}", timeout=8000)'
            )
        else:
            lines.append("    # no assertable outcome was available from the plan")
            lines.append('    await expect(page.locator("body")).to_be_visible(timeout=8000)')
            warnings.append(
                "flow has no concrete assertion: the expected outcome contained no "
                "quotable literal, so only page liveness is checked"
            )

    return "\n".join(lines) + "\n", warnings, None


def _value_expression(step: TestStep) -> str:
    """Python expression for a step's input value.

    A credential placeholder becomes a runtime secret lookup. A literal value
    is emitted as a string literal. Nothing else is ever inlined.
    """
    raw = step.value or ""
    match = SECRET_PLACEHOLDER_RE.search(raw)
    if match:
        name = (match.group(1) or match.group(2) or "username").lower()
        return f'ctx["secret"]("{name}")'
    lowered = f"{step.target} {step.description}".lower()
    if not raw and "password" in lowered:
        return 'ctx["secret"]("password")'
    if not raw and any(word in lowered for word in ("username", "email address", "user name")):
        return 'ctx["secret"]("username")'
    return f'"{escape_py_string(raw)}"'


def _quoted_literal(text: str) -> str:
    """The first quoted phrase in a description, which is usually the expected text."""
    if not text:
        return ""
    match = re.search(r"[\"'‘’“”]([^\"'‘’“”]{2,80})[\"'‘’“”]", text)
    return match.group(1).strip() if match else ""


def _regex_literal(text: str) -> str:
    return re.escape(str(text)).replace("\\", "\\\\")


def _docstring(flow: TestFlow) -> str:
    category = getattr(flow.category, "value", flow.category)
    outcome = (flow.expected_outcome or "no expected outcome stated").replace('"', "'")
    return f"{flow.name} [{category}] - expects: {outcome}"


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", str(text).lower()).strip("_") or "flow"


# ==========================================================================
# Writing files
# ==========================================================================
def render_module(
    test: GeneratedTest,
    flow: TestFlow,
    risk: RiskLevel,
) -> str:
    """Header + body: a file that ``pytest`` can run without the agent."""
    header = FILE_HEADER.format(
        flow_id=flow.id,
        flow_name=flow.name.replace('"', "'"),
        flow_name_lit=escape_py_string(flow.name),
        category=getattr(flow.category, "value", flow.category),
        risk=risk.value,
        expected=(flow.expected_outcome or "-").replace('"', "'"),
        expected_lit=escape_py_string(flow.expected_outcome or ""),
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ"),
        model=test.generated_by_model,
    )
    return header + test.source.rstrip() + "\n"


def write_tests(
    directory: Path,
    tests: Sequence[GeneratedTest],
    flows: Sequence[TestFlow],
    risk_lookup: dict[str, RiskLevel],
) -> list[GeneratedTest]:
    """Write every valid test plus the pytest harness. Returns the same list.

    A final credential scan runs against the rendered file, not just the body:
    the header interpolates the flow name and expected outcome, which are model
    output and could in principle echo something they should not.
    """
    directory.mkdir(parents=True, exist_ok=True)
    by_id = {f.id: f for f in flows}

    for test in tests:
        flow = by_id.get(test.flow_id)
        if flow is None or not test.valid or not test.source.strip():
            continue
        risk = risk_lookup.get(test.flow_id, RiskLevel.MEDIUM)
        rendered = render_module(test, flow, risk)
        if assert_no_secret_literals(rendered):
            log.error("refusing to write %s: rendered module contains a secret", test.flow_id)
            test.valid = False
            test.validation_error = "rendered module contained a credential literal"
            continue
        path = directory / f"{test.module_name}.py"
        path.write_text(rendered, encoding="utf-8")
        test.file_path = str(path)

    (directory / "conftest.py").write_text(CONFTEST_SOURCE, encoding="utf-8")
    (directory / "pytest.ini").write_text(PYTEST_INI, encoding="utf-8")
    (directory / "README.md").write_text(_suite_readme(tests), encoding="utf-8")
    return list(tests)


def _suite_readme(tests: Sequence[GeneratedTest]) -> str:
    written = [t for t in tests if t.file_path]
    lines = [
        "# Agent-generated test suite",
        "",
        "Every file in this directory was written by the Autonomous Test Orchestration",
        "Agent from a live crawl of the target application. No human wrote or edited a",
        "test here.",
        "",
        "## Running the suite yourself",
        "",
        "```bash",
        "pip install pytest pytest-asyncio playwright",
        "playwright install chromium",
        "# only if the target needs a login:",
        "export LOGIN_USERNAME=... LOGIN_PASSWORD=...",
        "pytest -q",
        "```",
        "",
        "## Files",
        "",
    ]
    for test in written:
        lines.append(
            f"- `{Path(test.file_path).name}` - {test.flow_id} {test.flow_name} "
            f"(authored by `{test.generated_by_model}`)"
        )
    skipped = [t for t in tests if not t.file_path]
    if skipped:
        lines += ["", "## Not generated", ""]
        for test in skipped:
            lines.append(
                f"- {test.flow_id} {test.flow_name}: "
                f"{redact_text(test.validation_error or 'no source produced')}"
            )
    return "\n".join(lines) + "\n"
